### ISSUE TITLE
Wii naming convention

### ISSUE THREAD

**Issue by ghost** [libretro-thumbnails/Nintendo_-_Wii#22]
Any idea how the naming conventions fit together? I'm assuming the No-Intro names are the guidelines, but how does that fit with what is recognized in Retroarch? Is there any way to update what games are recognized as in RA? Is it worthwhile to flip some of the Wii games to the No-Intro naming since the current uses "_" to correct for ":" vs using "-" ?

**Comment by ghost** [comment]
May be saying the same thing twice, but I've got a No-intro named version of everything I've previously uploaded. Would you want only Retroarch compatible version naming, only No-intro naming, or both added?

**Comment by RobLoach** [comment]
For most serial/CD disc media, it's [Redump](http://redump.org). For thumbnail filenames, `:` in the database name is replaced with `-` for platform compatibility.
https://github.com/libretro-thumbnails/libretro-thumbnails#usage

**Comment by RobLoach** [comment]
Redump and GameTDB is in there too https://www.gametdb.com/

**Comment by ghost** [comment]
Alright, for now I guess I'll just stick with what's recognized by RA, then if I can figure it out, (or more than likely someone else) can just set them up as symbolic links later on if/when No-intro is supported.
